openapi: 3.0.0
info:
    title: Mock API
    description: This is a mock API definition for frontend development.
    version: 1.0.0
servers:
    - url: http://localhost:3000
paths:
    /users:
        get:
            summary: Get list of users
            responses:
                "200":
                    description: A list of users
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: "#/components/schemas/User"
        post:
            summary: Create a new user
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/User"
            responses:
                "201":
                    description: User created
components:
    schemas:
        User:
            type: object
            properties:
                id:
                    type: integer
                    example: 1
                name:
                    type: string
                    example: John Doe
                email:
                    type: string
                    example: john.doe@example.com
